name: demo workflow
on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hellow world"
